---
to: packages/<%=package%>/src/components/<%=StoryCardName%>/<%=StoryCardName%>Visualization.js
---
import React from "react";
import PropTypes from "prop-types";

import { LineChart } from "@hackoregon/component-library";

const <%=StoryCardName%>Visualization = ({ isLoading, data }) => (
  <React.Fragment>
    {!isLoading && data && (
      <LineChart
        data={data}
        dataKey="year"
        dataValue="ridership"
        dataSeries="series"
        title="Autogenerated <%=StoryCardName%> File Plot"
      />
    )}
  </React.Fragment>
);

<%=StoryCardName%>Visualization.propTypes = {
  isLoading: PropTypes.bool,
  data: PropTypes.arrayOf(
    PropTypes.shape({
      year: PropTypes.number,
      ridership: PropTypes.number,
      series: PropTypes.string
    })
  )
};

export default <%=StoryCardName%>Visualization;
