import { DEMOGRAPHICS, UNIT_SIZES_AFFORDABILITY, DEFAULT_INCOME } from '../../utils/data-constants';

export const INITIAL_USER_STATE = {
  income: DEFAULT_INCOME,
  unitSize: UNIT_SIZES_AFFORDABILITY[0],
};

export const INITIAL_OTHER_STATE = {
  demographic: DEMOGRAPHICS[0],
  unitSize: UNIT_SIZES_AFFORDABILITY[0],
};

const UPDATE_USER_UNIT_SIZE = 'PARAMETERS/UPDATE_USER_UNIT_SIZE';
const UPDATE_USER_INCOME = 'PARAMETERS/UPDATE_USER_INCOME';

const UPDATE_OTHER_UNIT_SIZE = 'PARAMETERS/UPDATE_OTHER_UNIT_SIZE';
const UPDATE_OTHER_DEMOGRAPHIC = 'PARAMETERS/UPDATE_OTHER_DEMOGRAPHIC';

export const actionTypes = {
  UPDATE_USER_UNIT_SIZE,
  UPDATE_USER_INCOME,
  UPDATE_OTHER_DEMOGRAPHIC,
  UPDATE_OTHER_UNIT_SIZE,
};
