export const INITIAL_STATE = {};

const UPDATE_UNIT_SIZE = 'PARAMETERS/UPDATE_UNIT_SIZE';
const UPDATE_DEMOGRAPHIC = 'PARAMETERS/UPDATE_DEMOGRAPHIC';

export const actionTypes = {
  UPDATE_UNIT_SIZE,
  UPDATE_DEMOGRAPHIC,
};
