# Use node-modules instead of PnP
nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

# Optimize builds for Travis 
enableGlobalCache: true
compressionLevel: 0

yarnPath: .yarn/releases/yarn-berry.js
