import {
  DEMOGRAPHICS,
  HOUSING_TYPES,
  DEFAULT_INCOME,
  DEFAULT_NEIGHBORHOOD,
} from '../../utils/data-constants';

export const INITIAL_USER_STATE = {
  income: DEFAULT_INCOME,
  unitSize: HOUSING_TYPES[0],
};

export const INITIAL_OTHER_STATE = {
  demographic: DEMOGRAPHICS[0],
  unitSize: HOUSING_TYPES[0],
};

export const INITIAL_NEIGHBORHOOD_STATE = DEFAULT_NEIGHBORHOOD;

const UPDATE_USER_UNIT_SIZE = 'PARAMETERS/UPDATE_USER_UNIT_SIZE';
const UPDATE_USER_INCOME = 'PARAMETERS/UPDATE_USER_INCOME';

const UPDATE_OTHER_UNIT_SIZE = 'PARAMETERS/UPDATE_OTHER_UNIT_SIZE';
const UPDATE_OTHER_DEMOGRAPHIC = 'PARAMETERS/UPDATE_OTHER_DEMOGRAPHIC';

const UPDATE_NEIGHBORHOOD = 'PARAMETERS/SELECT_NEIGHBORHOOD';

export const actionTypes = {
  UPDATE_USER_UNIT_SIZE,
  UPDATE_USER_INCOME,
  UPDATE_OTHER_DEMOGRAPHIC,
  UPDATE_OTHER_UNIT_SIZE,
  UPDATE_NEIGHBORHOOD,
};
