/*
 *
 * Migration constants
 *
 */

export const NAME = 'migration';
export const NON_ACTION_TYPE = '30px';

export const INITIAL_STATE = {
};

const GET_MIGRATION_DEMO = 'HOMELESSNESS/MIGRATION/DEMO/GET';
const GET_MIGRATION_DEMO_SUCCESS = 'HOMELESSNESS/MIGRATION/DEMO/GET/SUCCESS';
const GET_MIGRATION_DEMO_FAILURE = 'HOMELESSNESS/MIGRATION/DEMO/GET/FAILURE';


export const actionTypes = {
  GET_MIGRATION_DEMO,
  GET_MIGRATION_DEMO_SUCCESS,
  GET_MIGRATION_DEMO_FAILURE,
};
