name: Automatically review pull request
on: [pull_request]
jobs:
  auto-review-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Approve pull requests from approved actors
        if: github.actor == 'jaronheard'
        uses: andrewmusgrave/automatic-pull-request-review@0.0.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          event: APPROVE
          body: 'To go fast, go alone.'