name: "Chromatic"
on: push
    paths-ignore:
    - '**.yml'
    - '**.md'
    - 'Makefile'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          yarn && yarn bootstrap
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          autoAcceptChanges: true
